---
# tasks file for sshkeygen
- name: 在本地创建临时文件目录
  local_action: file dest={{local_ssh_dir}} state=directory

- name: 关闭首次登录询问yes/no
  lineinfile:
    path: /etc/ssh/ssh_config
    regexp: 'StrictHostKeyChecking'
    line: 'StrictHostKeyChecking no'
  when: inventory_hostname in groups.master

- name: 生成密钥
  openssh_keypair: path=/root/.ssh/id_rsa size=3072
  when: inventory_hostname in groups.master

- name: 将密钥从远端复制至本地
  fetch:
    src: /root/.ssh/id_rsa.pub
    dest: {{ ssh_dir }}
  when: inventory_hostname in groups.master

- name: 将公钥追加到同一个文件
  #  local_action: shell find {{ ssh_dir }}/{{ inventory_hostname }}/* -type f -exec sh -c 'cat {}>> {{ ssh_dir }}/authorized_keys' \;
  local_action:
    file: dest={{local_ssh_dir}}/authorized_keys state=touch
    lininfile:
      dest: "{{local_ssh_dir}}/authorized_keys"
      line: "{{lookup('file', '{{item}}')}}"
    with_items:
      - "{{ocal_ssh_dir}}/{{inventory_hostname}}/root/.ssh/id_rsa.pub"
  when: inventory_hostname in groups.master

- name: 配置互信
  authorized_key:
    user: root
    key: "{{ lookup('file', {{ local_ssh_dir }}/authorized_keys) }}"
    path: '/root/.ssh/authorized_keys'
    manage_dir: no
    state: present
