---
# tasks file for roles/kernel
- setup:
  register: res

- block:
  - name: 导入密钥
    shell: rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
    
  - name: 安装YUM源
    ignore_errors: yes
    yum: name=https://www.elrepo.org/elrepo-release-7.0-4.el7.elrepo.noarch.rpm state=latest
  
  - name: 安装kernel
    yum:
      name: kernel-ml
      disablerepo: "*"
      enablerepo: "elrepo-kernel"
      state: present
  
  - name:
    lineinfile:
      path: "/etc/default/grub"
      regexp: "^GRUB_DEFAULT=.*"
      line: "GRUB_DEFAULT=0"
  
  - name:
    shell: grub2-mkconfig -o /boot/grub2/grub.cfg

  - name: reboot
    shell: reboot
  when: res.ansible_facts.ansible_kernel is version('4.18', '<')
