---
# tasks file for common
# ALL Nodes

- name: 禁用Firewalld和dnsmasq
  systemd:
  - name:
    - firewalld
    - dnsmasq
    state: stop
    enabled: no

- name: 禁用Selinux
  lineinfile:
    dest: /etc/selinux/config
    regexp: '^SELINUX='
    line: SELINUX=disabled

- name: 设置主机名
  shell: hostnamectl set-hostname {{ node_name|quote }}

- name: 关闭swap
  lineinfile:
    dest: /etc/fstab
    regexp: '^(.*swap.*)$'
    line: '# \1'

- name: 即时生效
  shell: setenforce 0; swapoff -a

- name: 添加hosts
  template: src=hosts.j2 dest=/etc/hosts

- name: 同步时间
- block:
    yum: name: chrony state: present
    copy: src=files/chrony.conf dest=/etc/chrony.conf
    systemd: name=chronyd state=restarted enabled=yes

- name: 安装基本工具
  yum:
  - name:
    - wget
    - git
    - jq
    - psmisc
    - vim
    - net-tools
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    state: present

- name: 设置YUM源
- block:
    get_url: url=https://mirrors.aliyun.com/repo/Centos-8.repo dest=/etc/yum.repos.d/CentOS-Base.repo
    # yum: name=https://mirrors.aliyun.com/epel/epel-release-latest-8.noarch.rpm state=present
    # shell: sed -i 's|^#baseurl=https://download.fedoraproject.org/pub|baseurl=https://mirrors.aliyun.com|' /etc/yum.repos.d/epel*
    # shell: sed -i 's|^metalink|#metalink|' /etc/yum.repos.d/epel*
    shell: yum clean all && yum makecache

- name: Install IPVS
- block:
    yum:
    - name:
      - ipvsadm
      - ipset
      - sysstat
      - conntrack
      - libseccomp
      state: present
    copy: src=files/ipvs.conf dest=/etc/modules-load.d/ipvs.conf
    systemd: name=systemd-modules-load state=started enabled=yes

- name: 配置内核参数
  copy: src={{item.src}} dest={{item.dest}}
  with_items:
    - {src: "k8s.conf", dest: "/etc/sysctl.d/k8s.conf"}
    - {src: "limits.conf", dest: "/etc/security/limits.conf"}

- name: Update system
  yum:
  - name: '*'
    state: latest

- name: Restart server
  shell: reboot

- name: Wait for server to restart
  wait_for:
    port=22
    delay=1
    timeout=300
