---
- name: 0.系统初始化
  gather_facts: false
  hosts: all 
  roles:
    - common
    - sshkeygen
  tags: common 

- name: 1.自签证书 & 解压k8s组件二进制文件 
  gather_facts: false
  hosts: localhost 
  roles:
    - tls
    - binfiles
  tags: tls

- name: 2.创建kubeconfig
  gather_facts: false
  hosts: master01
  roles:
    - kubeconfig
  tags: kubeconfig

- name: 3.部署Docker
  gather_facts: false
  hosts: k8s 
  roles:
    - docker 
  tags: docker

- name: 3.部署ETCD集群
  gather_facts: false
  hosts: etcd
  roles:
    -  etcd
  tags: etcd

- name: 4.部署高可用
  gather_facts: false
  hosts: lb
  roles:
    - ha
  tags: ha

- name: 5.部署K8S Master
  gather_facts: false
  hosts: master
  roles:
    - master
    - startup
  tags: master

- name: 6.授权
  gather_facts: false
  hosts: master01
  roles:
    - bootstrap
  tags: bootstrap

- name: 7.部署K8S Worker
  gather_facts: false
  hosts: k8s 
  roles:
    - worker
  tags: worker

- name: 8.部署插件
  gather_facts: false
  hosts: master01
  roles:
    - addons
  tags: addons
