---
# tasks file for starup
- name: 启动haproxy
  systemd: name=haproxy state=restart enabled=yes daemon-reload=yes

- name: 启动kube-apiserver
  systemd: name=kube-apiserver state=restart enabled=yes daemon-reload=yes

- name: 启动keepalived
  systemd: name=keepalived state=restart enabled=yes daemon-reload=yes

- name: 等待HA启动
  wait_for: host={{vip}} port={{vip_port}} delay=5

- name: 启动kube-controller-manager
  systemd: name=kube-controller-manager state=restart enabled=yes daemon-reload=yes

- name: 启动kube-scheduler
  systemd: name=kube-scheduler state=restart enabled=yes daemon-reload=yes

  # - name: 启动kubelet
  #   systemd: name=kubelet state=restart enabled=yes daemon-reload=yes
  # 
  # - name: 启动kube-proxy
  #   systemd: name=kube-proxy state=restart enabled=yes daemon-reload=yes
  # 
  # - name: 查看集群状态
  #   shell: sleep 3 && kubectl get cs
  #   register: cs
  # 
  # - name:
  #   debug: var=cs.stdout_lines
